spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.routes[0].id=movie-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://MOVIE-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/movies/**

spring.cloud.gateway.server.webflux.routes[1].id=theatre-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://THEATRE-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/theatre/**

spring.cloud.gateway.server.webflux.routes[2].id=screen-controller
spring.cloud.gateway.server.webflux.routes[2].uri=lb://THEATRE-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/screen/**

spring.cloud.gateway.server.webflux.routes[3].id=seat-controller
spring.cloud.gateway.server.webflux.routes[3].uri=lb://THEATRE-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/seat/**

